Add actuator tests
gobgob/chariot-elevateur pull request #1
Opened 2019-04-07 08:24 UTC by fabien0102

Just to versionned this file somewhere, it's my g-code controller for the fork 😅 

It works with the real robot pcb and have everything working except the sensors 😉

2019-04-07 16:24 UTC, fabien0102 commented on low_level/ActuatorMgr.h
> +        theta<0: pointe vers le bas (�jection du palet)
🤔 J’vais régler ça ^^

2019-04-11 07:15 UTC, fabien0102 commented
@sylvaing19 Les trois axes sont fonctionnels !

2019-04-11 08:55 UTC, sylvaing19 requested changes
Au travail ! 😛

2019-04-11 08:55 UTC, sylvaing19 commented on low_level/ActuatorMgr.h
> +                m_aim_position.z = m_current_position.z - 20;
Alors oui mais non, moi je voulais la position "home" en butée sur le fin de course, c'est quoi le problème avec ça ?

2019-04-11 08:55 UTC, sylvaing19 commented on low_level/ActuatorMgr.h
> +        theta<0: pointe vers le bas (éjection du palet)
encodage ?

2019-04-11 08:55 UTC, sylvaing19 commented on low_level/ActuatorMgr.h
> +        z (mm) déplacement vertical
encodage ?

2019-04-11 08:55 UTC, sylvaing19 commented on low_level/ActuatorMgr.h
> +        y (mm) déplacement latéral
encodage ?

2019-04-11 08:55 UTC, sylvaing19 commented on low_level/ActuatorMgr.h
> +        if (!(y >= ACT_MGR_Y_MIN && y <= ACT_MGR_Y_MAX)) {
C'est très moche d'avoir des print d'erreurs dans une méthode de ce type, car au sein de cette méthode ce n'est pas une erreur, ce n'est une erreur que pour certains cas d'usage de la méthode.
C'est typiquement le genre de méthode qui est sensée retourner rapidement et pouvoir être appelée sans restrictions. Si tu veux absolument pouvoir savoir quelle dimension est hors limites, il faut que cette méthode te renvoie plus d'infos (3 booléens), traiter cette info et renvoyer des erreurs en conséquences. Car ton print_err ne te diras pas d'où la méthode a été appelée (t'as pas la stack trace) donc ça te fais une belle jambe quand tu la  vois dans ta console...
Il se trouve que pour le moment cette méthode n'est utilisée qu'à un seul endroit donc ça passe, mais plus tard on risque d'être emmerdé.

2019-04-11 09:02 UTC, fabien0102 commented on low_level/ActuatorMgr.h
> +                m_aim_position.z = m_current_position.z - 20;
Ba c’est pas ouf pour le fin de course mécaniquement parlant, et c’est plus jolie quand c’est à `-20` ;)

2019-04-11 09:02 UTC, fabien0102 commented on low_level/ActuatorMgr.h
> +        theta<0: pointe vers le bas (éjection du palet)
probablement ^^

2019-04-11 09:09 UTC, fabien0102 commented on low_level/ActuatorMgr.h
> +        if (!(y >= ACT_MGR_Y_MIN && y <= ACT_MGR_Y_MAX)) {
Ça facilite drôlement le debuggage pour l’instant, après j’entends l’idée de la stacktrace.

Normalement, si tout se passe bien, on veut toujours que cette méthode nous retourne `true`, c’est un garde fou pour pas péter la méca, du coup si c’est `false` j’aime bien le savoir direct.

Pour l’instant j’avais "ACT_UNREACHABLE" dans la console qui m’était encore moins utile ^^, l’idée était juste d’avoir un plus d’info qu’actuellement pour la phase de debug ;)

2019-04-11 09:10 UTC, fabien0102 commented on low_level/ActuatorMgr.h
> +        if (!(y >= ACT_MGR_Y_MIN && y <= ACT_MGR_Y_MAX)) {
Je peux déporter cette logique avec 3 booléens, mais j’avoue que j’trouve ça moins pratique

2019-04-11 09:18 UTC, sylvaing19 commented on low_level/ActuatorMgr.h
> +                m_aim_position.z = m_current_position.z - 20;
Si c'est esthétique, je te laisse choisir la valeur qui rends le mieux et ajouter un commentaire ;)

2019-04-11 09:22 UTC, sylvaing19 commented on low_level/ActuatorMgr.h
> +        if (!(y >= ACT_MGR_Y_MIN && y <= ACT_MGR_Y_MAX)) {
franchement, t'as 3 valeurs à mettre dans une fenêtre, c'est pas très compliqué à faire non ? T'as vraiment besoin de savoir laquelle des trois est en dehors ?
Je suis d'accord que ça facilite le débug, mais c'est un hack moche donc ça n'a rien à faire en prod ^^
Je préfère si on se contente du "ACT_UNREACHABLE" qui donne assez d'info pour corriger le problème

2019-04-12 07:49 UTC, merged

2019-04-12 07:50 UTC, fabien0102 commented on low_level/ActuatorMgr.h
> +            if (theta < ACT_MGR_THETA_MIN | theta > ACT_MGR_THETA_MAX) {
@sylvaing19 Tu feras gaffe, `|` ça compile pas :angel: (j’ai vu ça hier soir, j’ai pas eu le temps de commit ^^)

2019-04-12 07:52 UTC, fabien0102 commented on low_level/ActuatorMgr.h
> +            if (theta < ACT_MGR_THETA_MIN | theta > ACT_MGR_THETA_MAX) {
Ah, et `theta` est pas accessible dans ce scope aussi il parrait ^^